import Head from 'next/head'
import TaskList from '@/components/TaskList'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import NavBar from '@/components/NavBar'
import { PrismaClient } from '@prisma/client'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export default function Home({tasks}) {
  return (
    <>
      <Head>
        <title>Happy Helpers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-teal-400 to-teal-800">
        <NavBar />
        <div className="flex">
        <Sidebar />
        <TaskList tasks={tasks} />
        </div>
      </main>

      <Footer />
    </>
  )
}

export async function getServerSideProps() {
  const prisma = new PrismaClient();
  const tasks = await prisma.task.findMany();
  
  return {
    props: { tasks }
  }
}