import Head from 'next/head'
import TaskList from '@/components/TaskList'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import NavBar from '@/components/NavBar'
import { PrismaClient } from '@prisma/client'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Happy Helpers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="{styles.main}">
        <NavBar />
        <div className="flex">
        <Sidebar />
        <TaskList />
        </div>
      </main>

      <Footer />
    </>
  )
}