import Head from "next/head"
import NavBar from "@/components/NavBar"
import Footer from "@/components/Footer"
export default function ProfilePage(props) {
  return (
    <>
      <Head>
        <title>Happy Helpers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-neutral-100">
        <NavBar />
      </main>
      <Footer />
    </>
  )
}