//////////////////////
// Profile Page
//////////////////////

import Head from "next/head";

// Component dependencies
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Button from "@/components/Button";

export default function ProfilePage(props) {
  // Template
  return (
    <>
      <Head>
        <title>Happy Helpers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-neutral-100">
        <NavBar />
        <div>
          <h1>Fred Frederick</h1><br></br>
          <Button buttonName='Edit Profile'/>
          <br></br>
          <h1>Address:</h1>
          <p>12 Maple Ave,<br></br>
            Rockland, ON</p><br></br>
          <h1>Phone Number:</h1>
          <p>613.935.2024</p><br></br>
          <h1>Skills:</h1>
          <p>Tech support<br></br>
            Lawn Mowing<br></br>
            Cooking<br></br>
            Carpentry</p><br></br>
          <h1>Organizations:</h1>
          <p>Meals on Wheels</p><br></br>
          <h1>Description:</h1>
          <p>I am a happy helper!</p><br></br>
        </div>
      </main>
      <Footer />
    </>
  );
}